#==================================================================================================================
#
# Project:	MPC for multirotor systems.
#
# function:	MPC Position controller parameters
#
# Author:	Mina Kamel	mina.kamel@ethz.ch
#
# Ge:nerated:	03-Apr-2015 13:11:59
#
#==================================================================================================================

## Controller Parameters:
mass: 1.0
roll_time_constant: 0.1573
roll_gain: 1.076
pitch_time_constant: 0.1581
pitch_gain: 1.057
drag_coefficients: [0.1, 0.1, 0.1]

q_x: 150
q_y: 150
q_z: 80

q_vx: 0
q_vy: 0
q_vz: 0

q_roll: 60
q_pitch: 60

r_roll: 30
r_pitch: 30
r_thrust: 5

r_droll: 0.26
r_dpitch: 0.26
r_dthrust: 0.01

roll_max: deg(70.0)
pitch_max: deg(70.0)
yaw_rate_max: deg(90)
thrust_min: 3.81
thrust_max: 36.81

K_yaw: 1.8

Ki_xy: 0.8
Ki_z: 0.3
position_error_integration_limit: 0.1
antiwindup_ball: 0.1

enable_offset_free : false
enable_integrator : false

sampling_time: 0.0078    #IMPORTANT: set this equal to the rate of odometry msg
prediction_sampling_time: 0.05
