#==================================================================================================================
#
# Project:	MPC for multirotor systems.
#
# function:	MPC Position controller parameters
#
# Author:	Mina Kamel	mina.kamel@ethz.ch
#
# Ge:nerated:	03-Apr-2015 13:11:59
#
#==================================================================================================================

## Controller Parameters:
mass: 1.0
roll_time_constant: 0.164
pitch_time_constant: 0.160
roll_gain: 1.12
pitch_gain: 1.11
drag_coefficients: [ 0.1 , 0.1, 0.1]

q_x: 40
q_y: 40
q_z: 60

q_vx: 20
q_vy: 20
q_vz: 25

q_roll: 60
q_pitch: 60

r_roll: 35
r_pitch: 35
r_thrust: 2

r_droll: 1.6
r_dpitch: 1.6
r_dthrust: 0.0025

roll_max: deg(10.0)
pitch_max: deg(10.0)
yaw_rate_max: deg(90)
thrust_min: 5
thrust_max: 20

K_yaw: 1.8

Ki_xy: 10.8
Ki_z: 0.3
position_error_integration_limit: 0.1
antiwindup_ball: 0.1

enable_offset_free : false
enable_integrator : false

sampling_time: 0.00104    #IMPORTANT: set this equal to the rate of odometry msg
prediction_sampling_time: 0.01
