#==================================================================================================================
#
# Project:	Nonlinear MPC for Hexacopter trajectory tracking.
#
# function:	NMPC Position controller parameters.
#
# Author:	Mina Kamel	mina.kamel@ethz.ch
#
# Generated:	20-Dec-2015 02:37:59
#
#==================================================================================================================

## Controller Parameters:
mass: 1.0
roll_time_constant: 0.1573
roll_gain: 1.076
pitch_time_constant: 0.1581
pitch_gain: 1.057
linear_drag_coefficients: [0.1, 0.1, 0.1]

# dynamic config default values:
q_x : 80
q_y : 80
q_z : 120

q_vx : 30
q_vy : 30
q_vz : 100

q_roll : 1
q_pitch: 1

r_roll  : 00
r_pitch : 00
r_thrust : 1

roll_max: deg(10.0)
pitch_max: deg(10.0)
thrust_min: 5
thrust_max: 37

K_yaw: 1.8

Ki_xy: 0.2
Ki_z: 0.3
position_error_integration_limit: 2.0
antiwindup_ball: 0.4

enable_offset_free : false
enable_integrator : false

sampling_time: 0.0078    #IMPORTANT: set this equal to the rate of odometry msg
prediction_sampling_time: 0.1